### ISSUE TITLE
Question: is there a way to add a vs-latitude and vs-longitude to populate lat/lng in model

### ISSUE THREAD

**Issue by mastermind1981** [vskosp/vsGoogleAutocomplete#1]
Hi,

First of all, congratulation for your great job.

I have a question/ enhancement to the directive : is it possible to add a vs-longitude / vs latitude that will populate the latitude/ longitude in the model?

Thanks in advance,

**Comment by vskosp** [comment]
HI

Yes, it is possible, I will do it.

Thanks!

**Comment by mastermind1981** [comment]
Great !!! Thanks
