### ISSUE TITLE
Getting rid of Placeholder text

### ISSUE THREAD

**Issue by austinthedeveloper** [vskosp/vsGoogleAutocomplete#10]
I'm having a strange problem with `vsGoogleAutocomplete` and Material Design. See this Plunker:

http://embed.plnkr.co/HQzx72fUNG5rMHnHNcHp/preview 

The issue is more obvious using Chrome, Firefox seems to hide placeholder text until it has been clicked. Basically, my inputs are getting populated with "Enter a Location" and they're messing with with my labels. 

The example above shows 3 versions: 
1. Normal MD input w/ no placeholder
2. Normal MD input w/ placeholder
3. MD input w/ placeholder and label removed. Animations disappear with this option.
4. Input pulled from the original Plunker

How are you able to overwrite the generated text or not get it in the first place? Option 3 is how I currently have this running but I'd like to get the animation back.

**Comment by olsynt** [comment]
Have you solve that ? how if so?

**Comment by austinthedeveloper** [comment]
You made me re-visit my Plunker and I came up with a new solution. The placeholder needs to be a binded value:

http://embed.plnkr.co/HQzx72fUNG5rMHnHNcHp/preview 

````
<input vs-google-autocomplete placeholder="{{test}}">
````

The controller would just define something blank:

`$scope.test = "";`

This is the best solution that I have found so far. If you just put placeholder as blank, it will get overwritten with "Enter a Location".

**Comment by batsauto** [comment]
I am using `angular 1.6` now and `angular md  1.1.1` and I am having the exact same issues that you have described. 
I have viewed your plunker and verified that your solution works with those versions of angular and angular MD but with my updated versions that is'nt a viable solution.
If anyone else can shed some light on this issue I would greatly appriciate it.
