### ISSUE TITLE
Uncaught Error: [$injector:modulerr]

### ISSUE THREAD

**Issue by bharathnalla** [vskosp/vsGoogleAutocomplete#14]
I get the following error when I add the bower component in my angular application. works fine when I remove it. I am using angular js 1.2.26.

Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.2.26/$injector/modulerr?p0=r

**Comment by vskosp** [comment]
This plugin support angularjs starting from v1.3.15.

**Comment by bharathnalla** [comment]
I have upgraded to 1.4.8 but still see similar issue after install the component. 
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.8/$

**Comment by TheeGrassHopper** [comment]
@vskosp I'm getting the same error

Error: [$injector:nomod] Module 'vsGoogleAutocomplete' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.9/$injector/nomod?p0=vsGoogleAutocomplete

**Comment by salimchami** [comment]
I think it's just the order of these imports in the index.html : 

```
        "dist/vs-google-autocomplete.min.js",
        "dist/vs-autocomplete-validator.min.js"
```

I'm using it too and when i reversed the order, it worked. So, you have to import `vs-google-autocomplete.js` first.

**Comment by bharathnalla** [comment]
Reversing the order worked for me too!
