### ISSUE TITLE
Postcode component

### ISSUE THREAD

**Issue by jameswyse** [vskosp/vsGoogleAutocomplete#2]
Hello!

The address components are super handy, would it be possible to add a `vs-postcode` directive? 
Thanks for the awesome module!

**Comment by vskosp** [comment]
Hello!

Yes, addition of `vs-postcode` directive is possible, but not all google addresses contain information about postal code.

Thanks for your feedback!

**Comment by kofronpi** [comment]
+1, and postal code could be set to '' if no info is available. Thanks !

**Comment by psykolm22** [comment]
Useful for addresse witch contain postal code PR #6

**Comment by igler** [comment]
+1
