### ISSUE TITLE
Accounting for sublocality

### ISSUE THREAD

**Issue by LeeroyJenks** [vskosp/vsGoogleAutocomplete#5]
getCity() relies on "locality" being available in the place object.
However, some places only have "sublocality" and no "locality".
Places like Brooklyn will show no city when this function is called.

by the way this module is pretty incredible, so thank you.

**Comment by LeeroyJenks** [comment]
I did a little hacky fix in the function getCity()
from this:
    

    function getCity(place) {
        var COMPONENT_TEMPLATE = { locality: 'long_name' },
    	    city = getAddrComponent(place, COMPONENT_TEMPLATE);
		return city;
    }

to this

    function getCity(place) {
        var COMPONENT_TEMPLATE = { locality: 'long_name' },
    	    city = getAddrComponent(place, COMPONENT_TEMPLATE);
          if (!city || city == '') {
            COMPONENT_TEMPLATE = { sublocality_level_1: 'long_name'},
            city = getAddrComponent(place, COMPONENT_TEMPLATE);
          }
		return city;
    }


I'm sure you can come up with a better fix, but I just wanted something quick for my application.

**Comment by vskosp** [comment]
Hi!

1. In the [Google Maps JavaScript API documentation](https://developers.google.com/places/supported_types#table3) about restriction of autocomplete results written the next: <i>"...The (cities) type collection instructs the Places service to return results that match `locality` or `administrative_area_level_3`..."</i>

2. In the [Google Places API example](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform), where it is shown how to parse address components, only `locality` type used for getting the city.

3. When I got place details for Brooklyn through the autocomplete, I have gotten New York city in the address component.

Write, if I understood something wrong.

If you need to get information about sublocality, I can add a new directive for parsing this address component.

Thanks you!

**Comment by LeeroyJenks** [comment]
Hey!
Thanks for the quick response. I think the issue is really with special areas that use sublocalities as cities.
The NYC area tends to be one of those, so locality actually displays nothing.
I'm using "384 Court Street Brooklyn NY United States" as an example.
When I log all possible "address_components" types, I get this list:

street_number
route
neighborhood
political
sublocality_level_1
sublocality
political
administrative_area_level_2
political
administrative_area_level_1
political
country
political
postal_code
postal_code_suffix

You'll notice in this list that "locality" and "administrative_area_level_3" are not found in that list, so when attempting to get the city using those types, the outcome is undefined. I think this is an oversight on Google's part, and something I'll make sure to bring to their attention.
I just wanted to bring it to your attention as well!

**Comment by vskosp** [comment]
I think, that detailed information of place for this address("384 Court Street Brooklyn NY United States") is not full. It should contain component with `type: "locality"` and `short/long name: "NY/New York"`.

I can only add directives, which will parse place details object for getting additional information about input address.

**Comment by LeeroyJenks** [comment]
Yeah I agree. The issue is that I tried it with a few addresses in Brooklyn, and it was the same issue. It is either incomplete, or google is using a structure that they have not documented for places like New York City.
Since my application is highly centered around New York, I have added my previously-mentioned script to account for those issues.
Thanks!

**Comment by roydukkey** [comment]
> Brooklyn and other parts of New York City do not include the city as part of the address. They use `sublocality_level_1` instead.

Google documents that NYC is different on their [Place Autocomplete Address Form](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform) example.
