### ISSUE TITLE
I don't the lat and lng value.

### ISSUE THREAD

**Issue by kyawmyintthein** [vskosp/vsGoogleAutocomplete#9]
js
$scope.address = {
        name: '',
        place: '',
        components: {
          placeId: '',
          streetNumber: '', 
          street: '',
          city: '',
          state: '',
          countryCode: '',
          country: '',
          postCode: '',
          location: {
            lat: '',
            long: ''
          }
        }
      };

html
 <input vs-google-autocomplete
                        class="form-control"
                        ng-model="address.name"
                        vs-place="address.place"
                        vs-place-id="address.components.placeId"
                         vs-street-number="address.components.streetNumber" 
                         vs-street="address.components.street"
                         vs-city="address.components.city"
                         vs-state="address.components.state"
                         vs-country-short="address.components.countryCode"
                         vs-country="address.components.country"
                         vs-post-code="address.components.postCode"
                         vs-latitude="address.components.location.lat"
                         vs-longitude="address.components.location.long"
                         name="address"
                 id="address"
                        type="text"
                        required />

                <span class="help-block"><b>Model: </b>{{address.name}}</span>
          <span class="help-block"><b>Place id: </b>{{address.components.placeId}}</span>
          <span class="help-block"><b>Street number: </b>{{address.components.streetNumber}}</span>
          <span class="help-block"><b>Street: </b>{{address.components.street}}</span>
          <span class="help-block"><b>City: </b>{{address.components.city}}</span>
          <span class="help-block"><b>State: </b>{{address.components.state}}</span>
          <span class="help-block"><b>Country code: </b>{{address.components.countryCode}}</span>
          <span class="help-block"><b>Country: </b>{{address.components.country}}</span>
          <span class="help-block"><b>Postcode: </b>{{address.components.postCode}}</span>
          <span class="help-block"><b>Latitude: </b>{{address.components.location.lat}}</span>
          <span class="help-block"><b>Longitude: </b>{{address.components.location.long}}</span>

![screen shot 2015-10-13 at 12 11 05 pm](https://cloud.githubusercontent.com/assets/3658706/10445333/a83c9fca-71a3-11e5-8d47-41acffc37b65.png)

**Comment by vskosp** [comment]
Hm... It works fine in the [demo](http://plnkr.co/edit/sdcIaQ?p=preview). Maybe I have typed other data in the input field?

![image](https://cloud.githubusercontent.com/assets/8910062/11326328/a7191eac-916f-11e5-9ea6-f11084dcea47.png)
